# Generated by Django 6.0.1 on 2026-06-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_due_date_payment_late_fee_payment_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
