# Generated by Django 6.0.4 on 2026-04-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
